on:
  schedule:
  # Every 3 days
  - cron: '21 18 * * *'
  # But also on push
  push:
    branches:
    - master


jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update database
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export OUTDIR=$(mktemp -d)
        sudo apt-get update
        sudo apt-get install -y unzip curl wget ca-certificates perl sed git bash p7zip
        bash ./update.sh
        # release all files
        wget -qO- https://github.com/c4milo/github-release/releases/download/v1.1.0/github-release_v1.1.0_linux_amd64.tar.gz | tar zxvf -
        mv github-release /usr/local/bin/github-release
        chmod +x /usr/local/bin/github-release
        VERSION=$(date +%Y%m%d.%H.%M)
        # First, make sure the files are updated - if not, don't release
        # Get the latest release
        LATESTDIR=$(mktemp -d)
        wget -qO $LATESTDIR/aircraft.csv.gz "https://github.com/katlol/tar1090-db/releases/latest/download/aircraft.csv.gz"
        wget -qO $LATESTDIR/db.tar "https://github.com/katlol/tar1090-db/releases/latest/download/db.tar"
        if cmp -s $OUTDIR/aircraft.csv.gz $LATESTDIR/aircraft.csv.gz && cmp -s $OUTDIR/db.tar $LATESTDIR/db.tar; then
          echo "No changes, not releasing"
          exit 0
        fi
        github-release katlol/tar1090-db $VERSION master "tar1090-db $VERSION" "$OUTDIR/*"
